config/routes.rb
Rails.application.routes.draw do
  devise_for :sign_ups
  devise_for :users
  resources :microposts
  resources :users
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 140 }, presence: true
end

app/models/sign_up.rb
class SignUp < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :microposts
  validates :name, presence: true
  attr_writer :login

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  before_action :authenticate_user!
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title ToyApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield
    br
    br
    - if user_signed_in?
      = link_to('Logout', destroy_user_session_path, method: :delete)

app/views/microposts/_form.html.slim
= form_with(model: micropost, local: true) do |form|
  - if micropost.errors.any?
      div id="error_explanation"
        h2
          = pluralize(micropost.errors.count, "error")
          prohibited this micropost from being saved:
        ul
        -  micropost.errors.full_messages.each do |message|
           li= message

  .field
    = form.label :content
    = form.text_area :content, id: :micropost_content


  .field
    = form.label :user_id
    = form.number_field :user_id, id: :micropost_user_id

  .actions
    = form.submit

app/views/microposts/edit.html.slim
h1 Editing Micropost
= render 'form', micropost: @micropost
=> link_to 'Show', @micropost
'|
= link_to 'Back', microposts_path

app/views/microposts/index.html.slim
p#notice
  = notice
h1 Microposts

table
  thread
    tr
      th Content
      th User
      th colspan="3"
    tr

  tbody
    - @microposts.each do |micropost|
      tr
        td = micropost.content
        td = link_to 'Show', micropost
        td = link_to 'Edit', edit_micropost_path(micropost)
        td = link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' }

br
= link_to 'New Micropost', new_micropost_path

app/views/microposts/new.html.slim
h1 New Micropost
= render 'form', micropost: @micropost
= link_to 'Back', microposts_path

app/views/microposts/show.html.slim
p#notice
  = notice
p
  strong> Content:
  = @micropost.content
p
  strong> User:
  = @micropost.user_id
=> link_to 'Edit', edit_micropost_path(@micropost)
'|
= link_to 'Back', microposts_path

app/views/users/_form.html.slim
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    .error_explanation
      h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      ul
      - user.errors.full_messages.each do |message|
        li = message

  .field
    = form.label :name
    = form.text_field :name, id: :name

  .field
    = form.label :email
    = form.text_field :email, id: :user_email

  .field
    = form.label :password
    = form.password_field :password

  .actions
    = form.submit

app/views/users/edit.html.slim
h1 Editing User
= render 'form', user: @user
=> link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
p#notice
  = notice
h1 Users

table
  thread
    tr
      th Name
      th Email
      th colspan="3"
    tr

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

app/views/users/new.html.slim
h2
  | Sign up
= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
  = devise_error_messages!
  .field
    = f.label :name
    br
    = f.text_field :email, autofocus: true, autocomplete: "text"
  .field
    = f.label :email
    br
    = f.email_field :email, autofocus: true, autocomplete: "email"
  .field
    = f.label :password
    - if @minimum_password_length
      em
        | (
        = @minimum_password_length
        |  characters minimum)
    br
    = f.password_field :password, autocomplete: "new-password"
  .field
    = f.label :password_confirmation
    br
    = f.password_field :password_confirmation, autocomplete: "new-password"
  .actions
    = f.submit "Sign up"
= render "devise/shared/links"

app/views/users/show.html.slim
p#notice
  = notice
p
  strong> Name:
  = @user.name
p
  strong> Email:
  = @user.email
p
  - if @user.microposts.first
    = @user.microposts.first.content
  - else
    This user has not posted yet.

=> link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path